/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_luomin_dubbing_Dubbing */

#ifndef _Included_com_luomin_dubbing_Dubbing
#define _Included_com_luomin_dubbing_Dubbing
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_luomin_dubbing_Dubbing
 * Method:    fdkdecodec
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_luomin_dubbing_Dubbing_fdkdecodec
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_luomin_dubbing_Dubbing
 * Method:    mixedpcm
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_luomin_dubbing_Dubbing_mixedpcm
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_luomin_dubbing_Dubbing
 * Method:    fdkencodec
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_luomin_dubbing_Dubbing_fdkencodec
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
